### ISSUE TITLE
Compact header option regression in the 1.3.0 update

### ISSUE THREAD

**Issue by Patrxgt** [shdwmtr/simply-dark#31]
Most of the icons on the right don't show up and on the left Steam's icon is misaligned and the text from the normal header still shows up when hovering over Steam's icon.

![obraz](https://github.com/user-attachments/assets/1ba94806-e496-4283-99e1-93b423972778)
![obraz](https://github.com/user-attachments/assets/1403a653-c4fe-493b-b01e-4615b3ab2983)

**Comment by clawdius** [comment]
Hello, I can't seem to reproduce the issue on my end, the compact header is working normally both on millennium beta and public release. Can you describe what steam version (public or beta) and millennium version (public or beta) do you use?

Or try restarting steam, javascripts on themes tend to be wonky at some time, and if the issue still persists after restarting steam 3-4 times, let me know.

**Comment by ShadowMonster99** [comment]
Make sure you have javascript enabled in Millennium settings, if your on the public release.

**Comment by Patrxgt** [comment]
> Hello, I can't seem to reproduce the issue on my end, the compact header is working normally both on millennium beta and public release. Can you describe what steam version (public or beta) and millennium version (public or beta) do you use?
> 
> Or try restarting steam, javascripts on themes tend to be wonky at some time, and if the issue still persists after restarting steam 3-4 times, let me know.

I'm using a stable build of Steam and beta version of Millenium (it happens on the stable build for me too though). The problems started after updating to the 1.3.0 version and no fiddling around with the options changed that.
