### ISSUE TITLE
Friend List update broke Compact View of it

### ISSUE THREAD

**Issue by dolixec** [shdwmtr/simply-dark#49]
![j4kPsbq](https://github.com/user-attachments/assets/2a0d7bf4-283d-49c0-abf8-d0979c380471)
As you can see, the avatars are getting out of their bounds in Compact View of Friends List

**Comment by clawdius** [comment]
Looks normal on my end (friends with compact list), are you sure you're using the latest simply dark version?

![image](https://github.com/user-attachments/assets/ca1a66ab-d1b3-4c16-9653-a07474d75f23)

**Comment by dolixec** [comment]
Did the thread on the wrong theme. Mea culpa
