### ISSUE TITLE
Collections view has default blue background

### ISSUE THREAD

**Issue by Sokol550** [shdwmtr/simply-dark#50]
For a few updates now the collections section has had the default blue steam background color. Probably just an oversight. A fix would be appreciated.

![image](https://github.com/user-attachments/assets/9a55a9e0-0a27-4e8a-9785-daa8cf12674d)
![image](https://github.com/user-attachments/assets/b98b7fba-ce75-454d-9fb6-6fab1308b014)

**Comment by clawdius** [comment]
Please update simply dark to the newest version, thank you!
