### ISSUE TITLE
Error when attempting to open theme settings

### ISSUE THREAD

**Issue by addderalll** [shdwmtr/simply-dark#53]
Whenever I try to open the theme settings, it gives me this error:

Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_9251263_8022c896960e5c48
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

When following the link provided by the error, it describes the error as:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]

Both Millenium and Simple Dark are completely up-to-date, and I am on the current Steam Client beta.

**Comment by clawdius** [comment]
Millennium doesn't play nicely with steam beta right now. I'm afraid the only solution is either you don't use Millennium or you go to the steam main branch.

**Comment by addderalll** [comment]
I've reverted to the stable build and it's working as intended now. Apologies!
