### ISSUE TITLE
Bug in the top panel

### ISSUE THREAD

**Issue by th3r1ko** [shdwmtr/simply-dark#55]
The top panel, which contains the play button, is completely transparent, instead of translucent(?). It can be difficult to understand what's underneath. Transparency effects in Windows are turned on

![изображение](https://github.com/user-attachments/assets/0c27babb-8c80-42e2-8df7-fdb2a4877f6b)
![изображение](https://github.com/user-attachments/assets/0b3528db-84a7-47cb-8012-ba7eee585938)

**Comment by clawdius** [comment]
Ok so it might be related to the **performance mode** on steam settings, so if you have it turned on, it might look like this
![image](https://github.com/user-attachments/assets/0318752a-8579-4bb3-839b-33136771f581)

But when it turned off, it looks like yours. 

So i fixed it, it will look like this now
![image](https://github.com/user-attachments/assets/e60b60a9-6f77-4869-afda-cefadbec4dd0)

Thanks for submitting the problem!
