### ISSUE TITLE
Wishlist and list of subscribed mods became blue again after the newest Steam update

### ISSUE THREAD

**Issue by Patrxgt** [shdwmtr/simply-dark#58]
![obraz](https://github.com/user-attachments/assets/7b5b33f9-60dc-4418-bd7d-45ab20e717d3)
As you can see, it's blue again, while it was properly themed before the newest Steam update.

![obraz](https://github.com/user-attachments/assets/220d349e-11b0-4eea-ab95-b5d24954fba9)
Same with the subscribed mods.

**Comment by Patrxgt** [comment]
Welp, it's blue again for some reason.

**Comment by shdwmtr** [comment]
Steam limitation. At the moment its not possible for Millennium to patch it
